{% set name = "qass-tools-analyzer" %}
{% set version = "2.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qass_tools_analyzer-{{ version }}.tar.gz
  sha256: ee35610cdb6f1947d91a8b06fb0b278a36382f634959b6450b2d4ca7b5a90e51

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.7
    - sqlalchemy >=1.4.36
    - tqdm >=4.64.0
    - deprecated >=1.2.13
    - numpy >=1.19.5
    - pandas >=1.1.5
    - mysql-connector-python
    - pymysql
    - PySide2

test:
  imports:
    - qass.tools.analyzer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://qass.net/qass-open-source
  summary: Analyzer package for qass_tools
  license: LGPL-3.0
  license_file:
    - COPYING
    - COPYING.LESSER

extra:
  recipe-maintainers:
    - ossmos
